services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    image: qgis-caddy-webdav:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - qgis_data:/srv
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    depends_on:
      - qgis

  qgis:
    build:
      context: qgis
      dockerfile: Dockerfile
    volumes:
      - qgis_data:/data
    restart: unless-stopped

volumes:
  qgis_data:
  caddy_data:
  caddy_config:
