services:
  caddy:
    build:
      context: caddy
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    volumes:
      - qgis_data:/data
    restart: unless-stopped
    env_file:
      - .env

    depends_on:
      - qgis
  qgis:
    build:
      context: qgis
      dockerfile: Dockerfile
    volumes:
      - qgis_data:/data
    restart: unless-stopped
volumes:

  qgis_data:

